<a href="https://colab.research.google.com/github/tankien76/CS114.K21/blob/master/Capstone_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Danh sách nhóm
- Đoàn Xuân Minh - MSSV: 18521093
- Lê Trần Phúc Nguyên - MSSV: 18521157
- Phan Quang Tấn - MSSV: 18521377


# Mô tả bài toán : Dự đoán chủ đề của một bài báo tiếng Anh
- Input: Một đoạn văn bản của một bài báo tiếng Anh (article)
- Output: Chủ đề của đoạn văn bản 

Code tham khảo: https://towardsdatascience.com/sarcasm-detection-step-towards-sentiment-analysis-84cb013bb6db

Code tham khảo: https://pythonspot.com/nltk-stop-words/

# Prepare dataset

Thực hiện cào dữ liệu (crawl data) từ các trang báo tiếng Anh nổi tiếng như : The Sun https://www.thesun.co.uk/ ,Dailymail https://www.dailymail.co.uk/home/index.html, Telepraph http://telegraph.co.uk/

Code Crawl : https://github.com/tankien76/CS114.K21/blob/master/CrawlerTest.ipynb

Tập dataset sau khi crawl gồm có hơn 2600 bài báo với 8 chủ đề khác nhau như : sport, tvshowbiz, femail,.... Mỗi chủ đề gồm có hơn 300 bài báo.

Xác thực và tạo ứng dụng PyDrive.

In [ ]:
!pip install PyDrive

In [ ]:
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

In [ ]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [ ]:
downloaded = drive.CreateFile({'id':"1o2zIVZBmqSJa8huDq_Nn8waeTksbH4KI"})
downloaded.GetContentFile('text_data.csv')

Import các thư viện:
- pandas : đọc dữ liệu file json
- numpy : xử lý dữ liệu text

In [ ]:
import pandas as pd, numpy as np, re

Đọc dữ liệu bằng thư viện pandas từ file text_data.csv

In [ ]:
dataset = pd.read_csv("text_data.csv", encoding='ISO 8859-1')
dataset.head()

article   category
0  PHOTOS of McDonalds restaurants and merchandis...  lifestyle
1  ARIESMarch 21 to April 20SATURN, the most powe...  lifestyle
2  BRITS are being tempted to fly abroad once loc...  lifestyle
3  DONNA Mitchell tried every fad diet in the boo...  lifestyle
4  FASHION fans can buy jeans and a sleeveless to...  lifestyle

Đưa dữ liệu article và category vào list tương ứng

In [ ]:
features = dataset['article']
labels = dataset['category']

Thực hiện chuyển đổi các nhãn dán thành số để dễ dàng thực hiện trong khi training và test model

In [ ]:
from sklearn import preprocessing
number = preprocessing.LabelEncoder()
labels= number.fit_transform(labels)

# Data Preprocessing
Tiến hành xử lý dữ liệu văn bản (article) :

- Loại bỏ các ký tự đặc biệt(dấu câu, số)
- Loại bỏ các stopword trong tiếng Anh

download punkt trong thư viện nltk để tách từ khi xử lý dữ liệu

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

download stopwords trong thư viện nltk để xử lý các từ không cần thiết trong tiếng anh

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

Import thư viện nltk để sử lý ngôn ngữ tự nhiên

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

Loại bỏ các ký tự đặc biệt như: dấu câu, số,...

In [ ]:
features = features.apply(lambda s : re.sub('[^a-zA-Z]', ' ', s))

Loại bỏ các stopword (các từ không ảnh hưởng đến nội dung của văn bản) trong tiếng Anh

In [ ]:
stop_words = set(stopwords.words('english'))
for i in range (len(features)):
  word_tokens = word_tokenize(features[i])

  filtered_sentence = [w for w in word_tokens if not w in stop_words]

  filtered_sentence = []

  for w in word_tokens:
      if w not in stop_words:
          filtered_sentence.append(w)

# Feature Engineering

Vector hóa dữ liệu văn bản bằng TF-IDF:
- TF: tần suất xuất hiện của 1 từ trong 1 văn bản
- IDF: tần suất nghịch của 1 từ trong 1 tập văn bản
- .fit: Máy học từ vựng và tính toán idf( tần suất nghịch của 1 từ trong tập các văn bản) của train set.

Tham khảo: https://towardsdatascience.com/how-sklearns-tf-idf-is-different-from-the-standard-tf-idf-275fa582e73d

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfIdfVec = TfidfVectorizer()
tfIdfVec.fit(features)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words=None, strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

Đưa dữ liệu văn bản về matrix để training model 

In [ ]:
tf_idf_x = tfIdfVec.transform(features)

Tiến hành chia dữ liệu train và test: theo tỉ lệ 80% training và 20% testing vì khi thực hiện theo tỉ lệ 70/30 thì độ chính xác của các thuật toán giảm

In [ ]:
from sklearn.model_selection import train_test_split
features_train, features_test, labels_train, labels_test = train_test_split(tf_idf_x.toarray(), labels, test_size = .2, random_state = 0)

# Chosing Model

Thêm thư viện sklearn gồm :
- Các model sử dụng : LinearSVC, Multinomial Naive Bayes, Random Forest

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier

Model Linear support classifier

In [ ]:
lsvc = LinearSVC()
lsvc.fit(features_train, labels_train)
print("Train accuracy: ",lsvc.score(features_train, labels_train))
print("Test accuracy: ",lsvc.score(features_test, labels_test))

Train accuracy:  0.9985775248933144
Test accuracy:  0.8920454545454546


Model Multinomial Naive Bayes

In [ ]:
mnb = MultinomialNB()
mnb.fit(features_train, labels_train)
print("train accuracy: ",mnb.score(features_train, labels_train))
print("Test accuracy: ",mnb.score(features_test, labels_test))

train accuracy:  0.9193930772878142
Test accuracy:  0.8352272727272727


Model Random Forest Classifier

In [ ]:
rfc = RandomForestClassifier(n_estimators = 10, random_state = 0)
rfc.fit(features_train, labels_train)
print("train accuracy: ",rfc.score(features_train, labels_train))
print("Test accuracy: ",rfc.score(features_test, labels_test))

train accuracy:  0.9957325746799431
Test accuracy:  0.7234848484848485


=> Qua accuracy của các model, ta thấy model Linear support classifier có độ chính xác cao nhất với 89,2% và model Random Forest bị overfitting vì số lượng dataset ít.

# Đánh giá Model

Để đánh giá performance của các model thì cách tính bằng accuracy không phản ánh chính xác dữ liệu được phân loại như thê nào vì vậy chúng ta cần 1 cách tính độ chính xác khác đó là **F1 Score**

F1-score: trung bình điều hòa giữa precision và recall

F1-score = 2*(precision * recall)/(precision+recall)

**Precision** được định nghĩa là tỉ lệ số điểm true positive trong số những điểm được phân loại là positive

Precision = TP/(TP+FP)
Với : TP(True positive), FP(False positive)

**Recall** được định nghĩa là tỉ lệ số điểm true positive trong số những điểm thực sự là positive

Recall=TP/(TP+FN) Với TP(True positive), FN(False negative)

Code tham khảo : https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

Model Linear support classifier

In [ ]:
y1_pred=lsvc.predict(features_test) #Lưu kết quả dự đoán của model LinearSVC vào biến y1_pred
f1 = f1_score(labels_test, y1_pred, average='macro')
print("F1 score: ",f1)

F1 score:  0.8861288110545362


Model Multinomial Naive Bayes

In [ ]:
y2_pred=mnb.predict(features_test) #Lưu kết quả dự đoán của model MultinomialNB vào biến y2_pred
f1 = f1_score(labels_test, y2_pred, average='macro')
print("F1 score: ",f1)

F1 score:  0.7461226600644999


Model Random Forest Classifier

In [ ]:
y3_pred=rfc.predict(features_test) #Lưu kết quả dự đoán của model RandomForest vào biến y3_pred
f1 = f1_score(labels_test, y3_pred, average='macro')
print("F1 score: ",f1)

F1 score:  0.7052716389326805


Dùng Confusion Matrix để trực quan hóa về F1 score của từng class

Code tham khảo: https://towardsdatascience.com/confusion-matrix-for-your-multi-class-machine-learning-model-ff9aa3bf7826

In [ ]:
confusion = confusion_matrix(labels_test, y1_pred)
print('Confusion Matrix')
print(confusion)

Confusion Matrix
[[52  1 10  0  0  0  1  5]
 [ 3 70  0  0  0  0  2  2]
 [ 5  1 52  1  2  2  2  1]
 [ 1  0  2 17  0  0  2  0]
 [ 0  0  1  0 60  0  0  0]
 [ 0  0  1  0  0 84  1  0]
 [ 4  3  2  0  0  2 72  0]
 [ 0  0  0  0  0  0  0 64]]


In [ ]:
from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(labels_test, y1_pred, target_names=['femail', 'films', 'health','lifestyle','sport','technology','travel','tvshowbiz']))


Classification Report

              precision    recall  f1-score   support

      femail       0.80      0.75      0.78        69
       films       0.93      0.91      0.92        77
      health       0.76      0.79      0.78        66
   lifestyle       0.94      0.77      0.85        22
       sport       0.97      0.98      0.98        61
  technology       0.95      0.98      0.97        86
      travel       0.90      0.87      0.88        83
   tvshowbiz       0.89      1.00      0.94        64

    accuracy                           0.89       528
   macro avg       0.89      0.88      0.89       528
weighted avg       0.89      0.89      0.89       528



In [ ]:
confusion = confusion_matrix(labels_test, y2_pred)
print('Confusion Matrix')
print(confusion)

Confusion Matrix
[[62  0  2  0  0  0  0  5]
 [ 6 66  0  0  0  0  2  3]
 [19  0 38  0  0  7  1  1]
 [10  1  2  0  0  1  8  0]
 [ 1  0  1  0 58  0  0  1]
 [ 1  1  1  0  0 81  2  0]
 [ 6  2  1  0  0  0 74  0]
 [ 1  0  0  0  0  0  1 62]]


In [ ]:
from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(labels_test, y2_pred, target_names=['femail', 'films', 'health','lifestyle','sport','technology','travel','tvshowbiz']))


Classification Report

              precision    recall  f1-score   support

      femail       0.58      0.90      0.71        69
       films       0.94      0.86      0.90        77
      health       0.84      0.58      0.68        66
   lifestyle       0.00      0.00      0.00        22
       sport       1.00      0.95      0.97        61
  technology       0.91      0.94      0.93        86
      travel       0.84      0.89      0.87        83
   tvshowbiz       0.86      0.97      0.91        64

    accuracy                           0.84       528
   macro avg       0.75      0.76      0.75       528
weighted avg       0.82      0.84      0.82       528



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
confusion = confusion_matrix(labels_test, y3_pred)
print('Confusion Matrix')
print(confusion)

Confusion Matrix
[[38  6 11  1  0  3  0 10]
 [ 1 69  2  0  1  0  2  2]
 [13  5 35  0  0  6  4  3]
 [ 5  0  2  9  0  2  4  0]
 [ 3  5  0  0 50  2  0  1]
 [ 3  4  5  0  1 72  0  1]
 [ 7  4  8  0  1  1 58  4]
 [ 7  4  1  0  0  0  1 51]]


In [ ]:
from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(labels_test, y3_pred, target_names=['femail', 'films', 'health','lifestyle','sport','technology','travel','tvshowbiz']))


Classification Report

              precision    recall  f1-score   support

      femail       0.49      0.55      0.52        69
       films       0.71      0.90      0.79        77
      health       0.55      0.53      0.54        66
   lifestyle       0.90      0.41      0.56        22
       sport       0.94      0.82      0.88        61
  technology       0.84      0.84      0.84        86
      travel       0.84      0.70      0.76        83
   tvshowbiz       0.71      0.80      0.75        64

    accuracy                           0.72       528
   macro avg       0.75      0.69      0.71       528
weighted avg       0.74      0.72      0.72       528



# Chương trình test

Nhập đoạn văn bản tiếng Anh muốn dự đoán

In [ ]:
print("Nhap: ")
ch=(str(input()))

Nhap: 
Last Thursday afternoon in San Francisco three men were out alone on the range at TPC Harding Park: Jordan Spieth, his caddie, Michael Greller, and his coach, Cameron McCormick. Spieth had finished his opening round of the US PGA Championship three-and-a-half hours earlier. He’d shot 73, three-over, and was eight-off the lead, tied 109th. Now he was sitting cross-legged, his arms draped over his knees, staring into the middle distance like the answers he was looking for were hiding somewhere down there at the far end of the range.  Earlier that day, the PGA Tour posted a short clip of Spieth talking about the one thing he’d like to be able to tell his younger self. “Let me think about this question for a second,” he says in the video, “the one thing about golf that I wish I knew then that I know now.” There’s a long pause, and then he comes up with his answer. “Honestly,” he said, laughing, “I wish I played with the mentality I had back then.”


Xử lý dữ liệu được đưa vào

In [ ]:
ch = re.sub(r'[^a-zA-Z]',' ',ch)
ch_tokens = word_tokenize(ch)
ch_sentence = [w for w in ch_tokens if not w in stop_words]
ch_val = tfIdfVec.transform([ch]).toarray()

Dự đoán chủ đề của văn bản đã nhập

In [ ]:
ch_pred=lsvc.predict(ch_val)

In [ ]:
if (ch_pred[0]==0):
  print('femail')
if (ch_pred[0]==1):
  print('films')
if (ch_pred[0]==2):
  print('health')
if (ch_pred[0]==3):
  print('lifestyle')
if (ch_pred[0]==4):
  print('sport')
if (ch_pred[0]==5):
  print('technology')
if (ch_pred[0]==6):
  print('travel')
if (ch_pred[0]==7):
  print('tvshowbiz')

sport
